const quotes = [
  'Regret for wasted time is more wasted time.',
  'Do not wait. The time will never be just right.',
  'Time is what we want most, but what we use worst.',
  'Lost time is never found again.',
  'The key is in not spending time, but in investing it.',
  'You may delay, but time will not.',
  'Time flies over us, but leaves its shadow behind.',
  'The future depends on what you do today.',
  'A year from now you may wish you had started today.',
  'Don’t count the days, make the days count.',
  'The bad news is time flies. The good news is you’re the pilot.',
  'Time you enjoy wasting is not wasted time.',
  'You cannot do a kindness too soon, for you never know how soon it will be too late.',
  'It’s not that we have little time, but more that we waste a good deal of it.',
  'Every moment is a fresh beginning.',
  'Your time is limited, so don’t waste it living someone else’s life.',
  'The trouble is, you think you have time.',
  'Now is the only time you own. Live, love, toil with a will.',
  'Lost time is never found again, so make the most of the present.',
  'You will never find time for anything. If you want time, you must make it.',
];
